### ISSUE TITLE
"register is not a function"

### ISSUE THREAD

**Issue by Thundernerd** [br41nslug/directus-extension-randomized#1]
Trying to get this to work but when I start up Directus I get an error saying "register is not a function"

- I'm running Directus 9.16.1 (the version mentioned in the readme) through docker.
- Cloned the repo, npm install, npm run build, moved the file according to the readme

**Comment by br41nslug** [comment]
Ah sorry, i see i have made an error in my README 😬 

Where i said `mv dist extensions/hooks/directus-websocket-subscribe` that should have been `endpoints` instead of `hooks` 🤦‍♂️ 
The readme has been updated please let me know if you're still running into problems with the updated path!
